### ISSUE TITLE
Issue generating dump from Excel file via command line

### ISSUE THREAD

**Issue by edgardmarx** [tomatophantastico/sparqlmap#25]
I am currently experiencing troubles when trying to convert an Excel sheet into RDF via command line,
can you help me with that?

```
sparqlmap --action=dump --ds.url=".../KPS_Ortstabelle mit Stellen.xlsx" --r2rmlfile="../stellen_mapping2.ttl" --ds.columnNameLineNumber=0 --ds.type=EXCEL
```

Mapping:

```
@prefix smap: <http://aksw.org/Projects/SparqlMap/vocab#> .
@prefix r2rml: <http://www.w3.org/ns/r2rml#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix hp: <http://purl.org/voc/hp/> .

<#TableView> r2rml:tableName "\"Tabelle1\"" .

###########################
# Stallen Mapping
###########################

<#VaterTriplesMap>
	r2rml:logicalTable <#TableView>;
	r2rml:subjectMap [ r2rml:template "http://pfarrerbuch.aksw.org/kps/stellen/{\"Ort\"}" 
	r2rml:class hp:Position .
	];
```

Output:
```
 Error processing command line options: Was passed main parameter '--ds.columnNameLineNumber=0' but no main parameter was defined in your arg class
```
When removing parameter --ds.columnNameLineNumber=0
```
21:14:52,828 [restartedMain] WARN   AbstractApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sparqlMapSetup': Unsatisfied dependency expressed through field 'dc'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'create' defined in class path resource [org/aksw/sparqlmap/common/DataContextFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.metamodel.DataContext]: Factory method 'create' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
21:14:52,850 [restartedMain] ERROR  SpringApplication : Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sparqlMapSetup': Unsatisfied dependency expressed through field 'dc'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'create' defined in class path resource [org/aksw/sparqlmap/common/DataContextFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.metamodel.DataContext]: Factory method 'create' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.aksw.sparqlmap.cli.SparqlMapStarter.startSparqlMap(SparqlMapStarter.java:85)
        at org.aksw.sparqlmap.cli.SparqlMapStarter.main(SparqlMapStarter.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'create' defined in class path resource [org/aksw/sparqlmap/common/DataContextFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.metamodel.DataContext]: Factory method 'create' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1134)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1028)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
        ... 22 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.metamodel.DataContext]: Factory method 'create' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 34 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
        at java.net.URI.create(URI.java:852)
        at org.apache.metamodel.factory.ResourcePropertiesImpl.getUri(ResourcePropertiesImpl.java:56)
        at org.apache.metamodel.factory.FileResourceFactory.accepts(FileResourceFactory.java:28)
        at org.apache.metamodel.factory.ResourceFactoryRegistryImpl.createResource(ResourceFactoryRegistryImpl.java:67)
        at org.aksw.sparqlmap.common.DataContextFactory.getResource(DataContextFactory.java:168)
        at org.aksw.sparqlmap.common.DataContextFactory.create(DataContextFactory.java:112)
        at org.aksw.sparqlmap.common.DataContextFactory$$EnhancerBySpringCGLIB$$875a6da6.CGLIB$create$0(<generated>)
        at org.aksw.sparqlmap.common.DataContextFactory$$EnhancerBySpringCGLIB$$875a6da6$$FastClassBySpringCGLIB$$4a880cd0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
        at org.aksw.sparqlmap.common.DataContextFactory$$EnhancerBySpringCGLIB$$875a6da6.create(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 35 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 40: d:/emarx/data/pcp-on-web/KPS_Ortstabelle mit Stellen.xlsx
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 50 more
```

**Comment by tomatophantastico** [comment]
Hi,

the problem might be related to the paths used for the file. Can you try to remove the quotation marks and the blank spaces in the file names? 

And are you using the latest release?

Best, Jörg

**Comment by edgardmarx** [comment]
yep, 

I am using the 
latest version;
I renamed the file, but I am still getting the same errors.

attached the file [KPS.xlsx](https://github.com/tomatophantastico/sparqlmap/files/1165549/KPS.xlsx)

**Comment by tomatophantastico** [comment]
Thanks, i am onto it.

**Comment by edgardmarx** [comment]
It seems there is a problem regarding path resolving on Windows.
When I moved the mapping and the source file to the same directory of the SPARQLMap app, it works.
